#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 󰣇  󱥔 

bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
picom &
polybar &
nitrogen --restore &
